# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JDQjeuRBusQaEUEwkTGnq_SrS4IzlMUE
"""

import os
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
import matplotlib
matplotlibuse("Agg")

import keras
from keras.applications.vgg16 import VGG16, preprocess_input, decode_predictions
from keras.preprocessing import image
import numpy as np

val_path = str('/mnt/fast-data16/datasets/ILSVRC/2012/clsloc/val')
n_val = len(os.listdir(val_path))
print('num of validation files: ', n_val)

'''
model = VGG16(weights = 'imagenet')
img_path = '/mnt/fast-data16/datasets/ILSVRC/2012/clsloc/val/'
img = image.load_img(filename, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
preds = model.predict(preprocess_input(x))
results = decode_predictions(preds, top=5)[0]
'''

""">>> from keras.applications.vgg16 import VGG16
Using TensorFlow backend.
>>> model = VGG16(weights = 'imagenet')
WARNING:tensorflow:From /home/xiao/.conda/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-03-27 00:31:46.829281: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2019-03-27 00:31:47.817611: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55effb312e60 executing computations on platform CUDA. Devices:
2019-03-27 00:31:47.817635: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce RTX 2080 Ti, Compute Capability 7.5
2019-03-27 00:31:47.817642: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (1): GeForce RTX 2080 Ti, Compute Capability 7.5
2019-03-27 00:31:47.817646: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (2): GeForce RTX 2080 Ti, Compute Capability 7.5
2019-03-27 00:31:47.817650: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (3): GeForce RTX 2080 Ti, Compute Capability 7.5
2019-03-27 00:31:47.840427: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3000000000 Hz
2019-03-27 00:31:47.841905: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55effb5e5fa0 executing computations on platform Host. Devices:
2019-03-27 00:31:47.841919: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-03-27 00:31:47.842247: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:19:00.0
totalMemory: 10.73GiB freeMemory: 10.53GiB
2019-03-27 00:31:47.842504: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 1 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:1a:00.0
totalMemory: 10.73GiB freeMemory: 10.53GiB
2019-03-27 00:31:47.842763: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 2 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:67:00.0
totalMemory: 10.73GiB freeMemory: 10.53GiB
2019-03-27 00:31:47.843015: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 3 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:68:00.0
totalMemory: 10.73GiB freeMemory: 10.51GiB
2019-03-27 00:31:47.843286: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0, 1, 2, 3
2019-03-27 00:31:47.847276: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-03-27 00:31:47.847286: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 1 2 3 
2019-03-27 00:31:47.847290: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N N N N 
2019-03-27 00:31:47.847293: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 1:   N N N N 
2019-03-27 00:31:47.847296: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 2:   N N N N 
2019-03-27 00:31:47.847299: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 3:   N N N N 
2019-03-27 00:31:47.848313: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10247 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:19:00.0, compute capability: 7.5)
2019-03-27 00:31:47.848524: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 10247 MB memory) -> physical GPU (device: 1, name: GeForce RTX 2080 Ti, pci bus id: 0000:1a:00.0, compute capability: 7.5)
2019-03-27 00:31:47.848730: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 10247 MB memory) -> physical GPU (device: 2, name: GeForce RTX 2080 Ti, pci bus id: 0000:67:00.0, compute capability: 7.5)
2019-03-27 00:31:47.848894: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 10221 MB memory) -> physical GPU (device: 3, name: GeForce RTX 2080 Ti, pci bus id: 0000:68:00.0, compute capability: 7.5)
>>> img_path = 'ILSVRC2012_val_00024774.JPEG'
>>> from keras.preprocessing import image
>>> from imagenet_utils import preprocess_input
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'imagenet_utils'
>>> img = image.load_image(img_path)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'keras.preprocessing.image' has no attribute 'load_image'
>>> img = image.load_img(img_path)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xiao/.conda/envs/py36/lib/python3.6/site-packages/keras_preprocessing/image/utils.py", line 102, in load_img
    raise ImportError('Could not import PIL.Image. '
ImportError: Could not import PIL.Image. The use of `array_to_img` requires PIL.
>>> from PIL import Image
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'PIL'
"""